import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const { isSignedIn } = useUser()

  const globalStatus = api.status.global.useQuery()
  const personalStatus = api.status.personal.useQuery()

  return (
    <>
      <Head>
        <title>CodeReal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {!isSignedIn && (
            <div className="flex justify-center">
              <SignInButton />
            </div>
          )}
          {isSignedIn && (
            <div className="flex justify-center">
              <SignOutButton />
            </div>
          )}
          <p className="text-2xl text-white">
            {globalStatus.data ? globalStatus.data.numAnswered : "Loading tRPC query..."}
          </p>
          <p className="text-2xl text-white">
            {personalStatus.data ? personalStatus.data.userId : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
